// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type TaskStartResponse struct {
	Success bool   `json:"success"`
	Token   string `json:"token"`
}

type User struct {
	ID             int    `json:"id"`
	LastFMUsername string `json:"lastFMUsername"`
}
