// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Album struct {
	ID     int     `json:"id"`
	Name   string  `json:"name"`
	Artist *Artist `json:"artist"`
}

type Artist struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type TaskStartResponse struct {
	Success bool   `json:"success"`
	Token   string `json:"token"`
}

type TopArtist struct {
	Artist *Artist `json:"artist"`
	Plays  int     `json:"plays"`
	Rank   int     `json:"rank"`
}

type TopArtists struct {
	Artists []*TopArtist `json:"artists"`
	Total   int          `json:"total"`
}

type Track struct {
	ID     int     `json:"id"`
	Name   string  `json:"name"`
	Artist *Artist `json:"artist"`
	Album  *Album  `json:"album"`
}

type User struct {
	ID             int    `json:"id"`
	LastFMUsername string `json:"lastFMUsername"`
}

type WhoKnows struct {
	Artist    *Artist `json:"artist"`
	User      *User   `json:"user"`
	Playcount int     `json:"playcount"`
}

type WhoKnowsAlbum struct {
	Album     *Album `json:"album"`
	User      *User  `json:"user"`
	Playcount int    `json:"playcount"`
}

type WhoKnowsAlbumResponse struct {
	Users []*WhoKnowsAlbum `json:"users"`
	Album *Album           `json:"album"`
}

type WhoKnowsResponse struct {
	Users  []*WhoKnows `json:"users"`
	Artist *Artist     `json:"artist"`
}
