version: 2
jobs:
  deploy:
    context:
      - gowon
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no root@$GOWON_HOST_IP "cd ./mirrorball && /bin/bash ./deploy.sh ../gowon"

workflows:
  version: 2
  deploy:
    jobs:
      - approve:
          type: approval

      - deploy:
          requires:
            - approve
